# Generated by Django 4.2.6 on 2023-11-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.CharField(default=-1, max_length=50),
        ),
    ]
