# Generated by Django 4.2.6 on 2023-11-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0002_user_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
