# Generated by Django 4.2.6 on 2023-11-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user_id',
        ),
    ]
