# Generated by Django 4.2.6 on 2023-11-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login_app', '0005_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='/stock_user.jpg', null=True, upload_to=''),
        ),
    ]
