# Generated by Django 4.2.6 on 2023-11-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login_app', '0006_remove_user_image_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
