# Generated by Django 4.2.6 on 2023-11-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login_app', '0007_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='/stock_user.jpg', upload_to='images/'),
        ),
    ]
