# Generated by Django 4.2.6 on 2023-11-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login_app', '0013_alter_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image_path',
            field=models.CharField(default='/user_image/default_user_image.jpg', max_length=5000),
        ),
    ]
