# Generated by Django 4.2.6 on 2023-11-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login_app', '0014_user_user_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='commission',
            field=models.CharField(default=5, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='hiring_price',
            field=models.CharField(default=20, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='wallet',
            field=models.CharField(default=100, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.CharField(default=100, max_length=50),
        ),
    ]
