# Generated by Django 4.2.4 on 2023-12-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login_app', '0015_employee_commission_employee_hiring_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.CharField(default=1000000, max_length=50),
        ),
    ]
