# Generated by Django 4.2.6 on 2023-12-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login_app', '0018_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='wallet',
            field=models.CharField(default=1000000, max_length=50),
        ),
    ]
