# Generated by Django 4.2.6 on 2023-12-06 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_app', '0010_property_admin_approval'),
        ('signup_login_app', '0016_alter_user_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('buyer_sends', models.CharField(max_length=50)),
                ('seller_receives', models.CharField(max_length=50)),
                ('agent_receives', models.CharField(max_length=50)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_admin_id', to='signup_login_app.user')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_agent_id', to='signup_login_app.user')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_buyer_id', to='signup_login_app.user')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_app.property')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_seller_id', to='signup_login_app.user')),
            ],
        ),
    ]
