# Generated by Django 4.2.6 on 2023-12-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='admin_id',
        ),
    ]
