# Generated by Django 4.2.6 on 2023-12-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_remove_transaction_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='agent_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='property_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller_id',
            field=models.CharField(max_length=50),
        ),
    ]
