# Generated by Django 4.2.6 on 2023-12-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_alter_transaction_agent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('earning_from', models.CharField(max_length=50)),
                ('earning_amount', models.CharField(max_length=50)),
            ],
        ),
    ]
