# Generated by Django 4.2.6 on 2023-12-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0004_admin_earning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_earning',
            name='id',
        ),
        migrations.AddField(
            model_name='admin_earning',
            name='earning_id',
            field=models.CharField(default='earning', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
