# Generated by Django 4.2.6 on 2023-12-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0005_remove_admin_earning_id_admin_earning_earning_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='admin_receives',
            field=models.CharField(default='some', max_length=50),
            preserve_default=False,
        ),
    ]
