# Generated by Django 4.2.6 on 2023-11-13 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup_login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('property_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('market_status', models.CharField(default='Available For Sale', max_length=50)),
                ('property_location', models.CharField(max_length=500)),
                ('property_size', models.CharField(max_length=50)),
                ('property_name', models.CharField(max_length=50)),
                ('property_price', models.CharField(max_length=50)),
                ('agent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_agent', to='signup_login_app.employee')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup_login_app.user')),
                ('support_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_support', to='signup_login_app.employee')),
            ],
        ),
    ]
