# Generated by Django 4.2.6 on 2023-11-14 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login_app', '0001_initial'),
        ('property_app', '0002_alter_property_agent_id_alter_property_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_agent', to='signup_login_app.employee'),
        ),
        migrations.AlterField(
            model_name='property',
            name='support_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_support', to='signup_login_app.employee'),
        ),
    ]
