# Generated by Django 4.2.6 on 2023-12-06 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login_app', '0018_alter_employee_employee_id'),
        ('property_app', '0010_property_admin_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_agent', to='signup_login_app.employee'),
        ),
        migrations.AlterField(
            model_name='property',
            name='support_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_support', to='signup_login_app.employee'),
        ),
    ]
