# Generated by Django 4.2.6 on 2023-12-08 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login_app', '0019_alter_employee_wallet'),
        ('property_app', '0011_alter_property_agent_id_alter_property_support_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='buyer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_buyer', to='signup_login_app.user'),
        ),
    ]
